Display CLI changelog with 'doppler changelog' command
DopplerHQ/cli pull request #147
Opened 2020-10-16 09:30 UTC by Piccirello

This pulls the changelog from cli.doppler.com/changes, which is a Cloudflare Worker that pulls it from GitHub.

<img width="507" alt="Screen Shot 2020-10-16 at 2 29 30 AM" src="https://user-images.githubusercontent.com/8296030/96241728-6d953b00-0f57-11eb-8b44-7cfd7259555c.png">

2020-10-19 18:39 UTC, rgmvisser submitted a review, later dismissed
This is great! A small addition, but really nice. Maybe we can also print something like:
`run 'doppler changelog' to see all our latest changes`?

2020-10-19 18:39 UTC, rgmvisser commented on pkg/cmd/update.go
> +		utils.Log("\nWhat's new:")
We should move this inside the if statement in guess we don't get a result.

2020-10-26 04:13 UTC, rgmvisser requested changes
back in your queue

2020-10-28 01:09 UTC, Piccirello commented
<img width="477" alt="Screen Shot 2020-10-27 at 6 09 25 PM" src="https://user-images.githubusercontent.com/8296030/97378448-94207380-187f-11eb-8b85-9ac9461cfae9.png">

2020-10-28 01:56 UTC, rgmvisser approved these changes

2020-10-28 02:20 UTC, merged