Add support for doppler completion installation for zsh
DopplerHQ/cli pull request #276
Opened 2021-10-25 23:22 UTC by Kunamatata

Closes ENG-2640

2021-10-25 23:28 UTC, Kunamatata commented on pkg/cmd/completion.go
> +				path = "/usr/local/share/zsh/site-functions"
After doing some research this folder seems like the best place to put the `_doppler` completion file.
However, we could also modify the `$fpath` variable and insert a custom directory (for example: ~/.zsh/completions/doppler/...` or some variation).

zsh looks in `$fpath` to find completion files and functions:
> The convention for autoloaded functions used in completion is that they start with an underscore; as already mentioned, the fpath/FPATH parameter must contain the directory in which they are stored. If zsh was properly installed on your system, then fpath/FPATH automatically contains the required directories for the standard functions.

2021-10-25 23:28 UTC, Piccirello approved these changes
Very nice! Pro tip: you can reference the corresponding linear ticket in the PR description using "Closes ENG-2640". That'll auto-link the tickets and mark it resolved once the PR is merged.

2021-10-25 23:29 UTC, Piccirello requested changes

2021-10-25 23:29 UTC, Piccirello commented on pkg/cmd/completion.go
> +			}
How does this handle being run on a different OS? It looks like we never set the path.

2021-10-25 23:35 UTC, Kunamatata commented on pkg/cmd/completion.go
> +			}
You are correct, I believe we don't need the check anymore. Seems like zsh installs in the same directories for different OS (unix based)

I installed `zsh` on my windows via WSL and the path was the same `/usr/local/share/zsh/site-functions`

Not sure about native windows without WSL.

2021-10-25 23:49 UTC, Kunamatata commented on pkg/cmd/completion.go
> +			if !utils.IsWindows() {
If Windows users use the "Windows Subsystem for Linux" the path for zsh remains the same.

2021-10-26 17:14 UTC, Piccirello commented on pkg/cmd/completion.go
> +			if !utils.IsWindows() {
Should we exit with an error when using Windows? The below code doesn't appear to handle `path` being nil.

2021-10-26 17:15 UTC, Piccirello commented
Can you squash all of your commits into one?

2021-10-26 17:26 UTC, Kunamatata commented on pkg/cmd/completion.go
> +			if !utils.IsWindows() {
What do you think of adding the following right underneath the variable declarations of the function and removing the `if !utils.isWindows()` check from inside the `zsh` check?
```go
if utils.IsWindows() {
	utils.Log("Completion files are not supported on windows currently. However you can use completion files with Windows Subsystem for Linux.")
	return
}
```

2021-10-27 03:13 UTC, Piccirello commented on pkg/cmd/completion.go
> +			if !utils.IsWindows() {
I like that since it's helpful to the user. We'll want to exit with an error since installation failed.

2021-10-27 19:03 UTC, Piccirello commented on pkg/cmd/completion.go
> +		}
Is this true for bash too? We may just want to guard this in the zsh section.

2021-10-27 19:29 UTC, Kunamatata commented on pkg/cmd/completion.go
> +		}
It is true for bash too. Windows native does not have bash. 
However if they use WSL they will be able to use bash and the setup will continue since `utils.IsWindows()` will return false on a WSL distro.

2021-10-27 20:55 UTC, Piccirello commented on pkg/cmd/completion.go
> +			utils.HandleError(fmt.Errorf("Completion files are not supported on windows currently. However you can use completion files with Windows Subsystem for Linux."))
nit: you can use `errors.New` here since we don't need a template string

```suggestion
			utils.HandleError(errors.New("Completion files are not supported on windows currently. However you can use completion files with Windows Subsystem for Linux."))
```

2021-10-28 01:49 UTC, Kunamatata commented on pkg/cmd/completion.go
> +			utils.HandleError(fmt.Errorf("Completion files are not supported on windows currently. However you can use completion files with Windows Subsystem for Linux."))
Resolved by 25e04da

2021-10-28 03:36 UTC, Piccirello reviewed
One last nit: the changelog for this repo is autogenerated by the commit messages. Given that this repo is exclusively for the CLI, you can remove the mention of the CLI from it.

"Add zsh completion support for doppler cli" -> "Add support for installing zsh completions"

2021-10-28 03:36 UTC, Piccirello commented on pkg/cmd/completion.go
> +			utils.HandleError(errors.New("Completion files are not supported on windows currently. However you can use completion files with Windows Subsystem for Linux."))
```suggestion
			utils.HandleError(errors.New("Completion files are not supported on Windows. You can use completion files with Windows Subsystem for Linux (WSL)."))
```

2021-10-28 20:17 UTC, Piccirello approved these changes
Congrats- you're now a CLI contributor 😃

2021-10-29 19:49 UTC, merged